### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by 177715031** [StevenBaby/chess#1]
大佬，请问这个怎么让AI先手呀，谢谢大佬

**Comment by StevenBaby** [comment]
目前不支持，有空我开发一下这个功能吧。

**Comment by 177715031** [comment]
我可以尝试加一个，应该不是很难，我本来打算也这么开发的，可是不太明白如何控制引擎行棋

**Comment by StevenBaby** [comment]
这个需求实现了，一会我上传一下。

关于控制引擎的，全部都实现在 engine.py 里。

具体 UCCI 的协议，参考：

<https://www.xqbase.com/protocol/cchess_ucci.htm>

**Comment by StevenBaby** [comment]
为了练习控制引擎，你可以尝试写一下，思考时间和深度的设置。欢迎 pr
